name: Go package

on: [ push ]

jobs:
  build:
    name: Build Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64
        goos: [ linux, windows ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: go build -o dist/

      - name: Archive built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bonita-application-packager
          path: dist