name: Build Bonita Application Packager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Go Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build binaries
        run: ./build-all-os.sh

      - name: Copy readme file
        run: cp README.md dist/

      - name: Archive built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bonita-application-packager
          path: dist
          retention-days: 10
