name: Release Bonita Application Packager
run-name: Release ${{inputs.version}} by @${{github.actor}}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        default: '0.0.0'
        required: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build binaries
        run: ./build-all-os.sh

      - name: Zip binaries
        run: zip -r dist/bonita-application-packager.zip dist/

      - name: Create Release
        id: create_release 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/bonita-application-packager.zip
          asset_name: bonita-application-packager-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip
