name: Release Bonita Application Packager
run-name: Release ${{inputs.version}} by @${{github.actor}}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        default: '0.0.0'
        required: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build binaries
        run: ./build-all-os.sh ${{ github.event.inputs.version }}

      - name: copy readme file
        uses: canastro/copy-file-action@master
        with:
          source: "README.md"
          target: dist

      - name: Zip binaries
        run: cd dist/ && zip -r bonita-application-packager-${{ github.event.inputs.version }}.zip .

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          generateReleaseNotes: true
          artifacts: "dist/bonita-application-packager-${{ github.event.inputs.version }}.zip"
